export const TEST = 'TEST';

/* VIEWS */
/* --- MAIN */
export const SET_MAIN_VIEW_PUZZLE_ERROR = 'SET_MAIN_VIEW_PUZZLE_ERROR';
export const SET_MAIN_VIEW_PUZZLE_ERROR_MESSAGE = 'SET_MAIN_VIEW_PUZZLE_FETCHED';
export const SET_MAIN_VIEW_PUZZLE_FETCHED = 'SET_MAIN_VIEW_PUZZLE_FETCHED';
export const SET_MAIN_VIEW_PUZZLE_FETCHING = 'SET_MAIN_VIEW_PUZZLE_FETCHING';
export const SET_MAIN_VIEW_PUZZLE_MATRIX = 'SET_MAIN_VIEW_PUZZLE_MATRIX';
export const SET_MAIN_VIEW_PUZZLE_STORAGE = 'SET_MAIN_VIEW_PUZZLE_STORAGE';
export const SET_MAIN_VIEW_PUZZLE_SQUARE = 'SET_MAIN_VIEW_PUZZLE_SQUARE';
export const SET_MAIN_VIEW_PUZZLE_SUBMISSION_MESSAGE = 'SET_MAIN_VIEW_PUZZLE_SUBMISSION_MESSAGE';
export const SET_MAIN_VIEW_PUZZLE_WIN_STATE = 'SET_MAIN_VIEW_PUZZLE_WIN_STATE';