export const TEST = 'TEST';

/* VIEWS */
/* --- MAIN PUZZLE */
export const SET_MAIN_VIEW_PUZZLE_ERROR = 'SET_MAIN_VIEW_PUZZLE_ERROR';
export const SET_MAIN_VIEW_PUZZLE_ERROR_MESSAGE = 'SET_MAIN_VIEW_PUZZLE_FETCHED';
export const SET_MAIN_VIEW_PUZZLE_FETCHED = 'SET_MAIN_VIEW_PUZZLE_FETCHED';
export const SET_MAIN_VIEW_PUZZLE_FETCHING = 'SET_MAIN_VIEW_PUZZLE_FETCHING';
export const SET_MAIN_VIEW_PUZZLE_MATRIX = 'SET_MAIN_VIEW_PUZZLE_MATRIX';
export const SET_MAIN_VIEW_PUZZLE_STORAGE = 'SET_MAIN_VIEW_PUZZLE_STORAGE';
export const SET_MAIN_VIEW_PUZZLE_SQUARE = 'SET_MAIN_VIEW_PUZZLE_SQUARE';
export const SET_MAIN_VIEW_PUZZLE_SUBMISSION_MESSAGE = 'SET_MAIN_VIEW_PUZZLE_SUBMISSION_MESSAGE';
export const SET_MAIN_VIEW_PUZZLE_FAIL_STATE = 'SET_MAIN_VIEW_PUZZLE_FAIL_STATE';
export const SET_MAIN_VIEW_PUZZLE_WIN_STATE = 'SET_MAIN_VIEW_PUZZLE_WIN_STATE';
/* --- MAIN TIMER */
export const INCREMENT_MAIN_VIEW_TIMER = 'INCREMENT_MAIN_VIEW_TIMER';
export const RESET_MAIN_VIEW_TIMER = 'RESET_MAIN_VIEW_TIMER';
export const SET_MAIN_VIEW_TIMER_ACTIVE = 'SET_MAIN_VIEW_TIMER_ACTIVE';
export const SET_MAIN_VIEW_TIMER = 'SET_MAIN_VIEW_TIMER';
export const SET_MAIN_VIEW_TIMER_STARTED = 'SET_MAIN_VIEW_TIMER_STARTED';
export const SET_MAIN_VIEW_TIMER_START_TIME = 'SET_MAIN_VIEW_TIMER_START_TIME';